// Build a Markdown "review document" from a set of papers: an optional
// synthesis narrative (the Q&A from the Synthesize panel) followed by an
// annotated bibliography (each paper's citation + its stored AI summary).
// Pure and unit-tested; the Tauri side only writes the resulting string.

import type { ChatMessage, Item, StoredSummary } from "../types";

export interface ReviewExportOptions {
  /** Heading scope, e.g. a collection name or "All Papers". */
  title: string;
  /** Display timestamp (passed in so this stays a pure function). */
  generatedAt: string;
  items: Item[];
  summaries: Map<string, StoredSummary>;
  /** The synthesis conversation, if exporting from the Synthesize panel. */
  narrative?: ChatMessage[];
}

function citation(item: Item): string {
  const parts = [
    item.creators.length ? item.creators.join(", ") : null,
    item.publication ?? null,
    item.year != null ? String(item.year) : null,
  ].filter(Boolean);
  const base = parts.length ? `*${parts.join(" · ")}*` : "";
  const doi = item.doi
    ? ` · DOI: [${item.doi}](https://doi.org/${item.doi})`
    : "";
  return base + doi;
}

export function buildReviewMarkdown(o: ReviewExportOptions): string {
  const n = o.items.length;
  const lines: string[] = [
    `# Review — ${o.title}`,
    "",
    `_Generated by Zotero Notebook · ${o.generatedAt} · ${n} ${n === 1 ? "paper" : "papers"}_`,
    "",
  ];

  if (o.narrative && o.narrative.length > 0) {
    lines.push("## Synthesis", "");
    for (const m of o.narrative) {
      if (m.role === "user") lines.push(`### ${m.content}`, "");
      else lines.push(m.content, "");
    }
  }

  lines.push("## Annotated bibliography", "");
  o.items.forEach((item, i) => {
    lines.push(`### ${i + 1}. ${item.title}`);
    const cite = citation(item);
    if (cite) lines.push(cite);
    lines.push("");
    const summary = o.summaries.get(item.key);
    lines.push(summary ? summary.summary : "_(no AI summary yet)_", "");
    if (item.tags.length > 0) {
      lines.push(`Tags: ${item.tags.map((t) => `\`${t}\``).join(", ")}`, "");
    }
  });

  return lines.join("\n");
}

/** A filesystem-safe default file name for the export. */
export function exportFileName(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 60);
  return `review-${slug || "papers"}.md`;
}
